<footer class="usa-footer">
      <div class="grid-container usa-footer__return-to-top">
        <a href="#">Return to top</a>
      </div>
      <div class="usa-footer__primary-section">
        <nav class="usa-footer__nav" aria-label="Footer navigation">
          <ul class="grid-row grid-gap">
            <!--<li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="/" alt="The home page and where I provide a little information about myself.">Home Page</a>
            </li>-->
            <li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="https://www.linkedin.com/in/piomghaffari/" alt="A link to my LinkedIn profile." target="_blank" rel="noopener noreferrer">LinkedIn</a>
            </li>
            <li class="mobile-lg:grid-col-4 desktop:grid-col-auto usa-footer__primary-content">
              <a class="usa-footer__primary-link" href="https://github.com/piomghaffari/piomghaffari.com" alt="A link to the GitHub repo for this page." target="_blank" rel="noopener noreferrer">GitHub Repo</a>
            </li>
          </ul>
        </nav>
      </div>
      <div class="usa-footer__secondary-section">
        <div class="grid-container">
          <div class="grid-row grid-gap">
            <div class="usa-footer__logo grid-row mobile-lg:grid-col-6 mobile-lg:grid-gap-2">
              <div class="mobile-lg:grid-col-auto">
                <img class="usa-footer__logo-img footer-circle" src="assets/images/profile.png" alt="A picture of Piom smiling.">
              </div>
              <div class="mobile-lg:grid-col-auto">
                <h3 class="usa-footer__logo-heading">Piom Ghaffari</h3>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>