<div class="usa-overlay"></div>
  <header class="usa-header usa-header--basic usa-header--megamenu">
    <div class="usa-nav-container">
      <div class="usa-navbar">
        <div class="usa-logo" id="basic-mega-logo">
          <em class="usa-logo__text"><a href="/" title="Home" aria-label="Home">Piom Ghaffari</a></em>
        </div>
        <button class="usa-menu-btn">Menu</button>
      </div>
      <nav aria-label="Primary navigation" class="usa-nav">
        <div class="usa-nav__inner">
          <button class="usa-nav__close"><img src="assets/uswds/img/close.svg" alt="close"></button>
          <ul class="usa-nav__primary usa-accordion">
            <li class="usa-nav__primary-item"><a class="usa-nav__link" href="/" alt="The home page and where I provide a little information about myself."><span>About Me</span></a></li>
            <li class="usa-nav__primary-item"><a class="usa-nav__link" href="https://www.linkedin.com/in/piomghaffari/" alt="My LinkedIn profile." target="_blank" rel="noopener noreferrer"><span>LinkedIn</span></a></li>
          </ul>
        </div>
      </nav>
    </header>