<div class="usa-section">
      <div class="grid-container">
        <div class="grid-row grid-gap">
          <div class="usa-layout-docs__sidenav desktop:grid-col-3">
            <nav aria-label="Secondary navigation">
              <ul class="usa-sidenav">
                <li class="usa-sidenav__item"><a href="/" alt="The home page and where I provide a little information about myself.">About Me</a></li>
                <li class="usa-sidenav__item"><a href="https://www.linkedin.com/in/piomghaffari/" alt="My LinkedIn profile" target="_blank" rel="noopener noreferrer">LinkedIn Profile</a></li>
              </ul>
            </nav>
          </div>
          <main class="usa-layout-docs__main desktop:grid-col-9 usa-prose usa-layout-docs" id="main-content">
            <h1>Error</h1>
            <p class="usa-intro">Sorry, didn't find that page!</p>
            <p>Click on any of the links on this page to try again.</p>
          </main>
        </div>
      </div>
    </div>